service: sls-api

frameworkVersion: "3"

custom:
  myStage: ${opt:stage, self:provider.stage}
  settings:
    dev:
      POSTS_TABLE: posts-dev
    prod:
      POSTS_TABLE: posts-prod

provider:
  name: aws
  runtime: nodejs12.x
  environment: ${self:custom.settings.${self:custom.myStage}}
  region: us-east-1
  iam:
    role:
      - statements:
          - Effect: "Allow"
            Action:
              - cloudwatch:*
              - dynamodb:DescribeTable
              - dynamodb:Scan
              - dynamodb:GetItem
              - dynamodb:PutItem
              - dynamodb:UpdateItem
              - dynamodb:DeleteItem
              - dynamodb:ListStreams
            Resource:
              - "arn:aws:dynamodb:${self:provider.region}:*:table/${self:custom.settings.${self:custom.myStage}.POSTS_TABLE}"
functions:
  createPost:
    handler: handler.createPost
    events:
      - http:
        path: /post
        method: post
  getAllPosts:
    handler: handler.getAllPosts
    events:
      - http:
          path: /posts
          method: get
  getPosts:
    handler: handler.getPosts
    events:
      - http:
          path: /posts/{number}
          method: get
  getPost:
    handler: handler.getPost
    events:
      - http:
          path: /post/{id}
          method: get
  updatePost:
    handler: handler.updatePost
    events:
      - http:
          path: /post/{id}
          method: put
  deletePost:
    handler: handler.deletePost
    events:
      - http:
          path: /post/{id}
          method: delete
  triggerStream:
    handler: handler.triggerStream
    events:
      - stream:
          type: dynamodb
          batchSize: 1
          startingPosition: LATEST
          arn:
            Fn::GetAtt:
              - PostsTable
              - StreamArn

resources:
  Resources:
    PostsTable:
      Type: AWS::DynamoDB::Table
      Properties:
        AttributeDefinitions:
          - AttributeName: "id"
            AttributeType: "S"
        KeySchema:
          - AttributeName: "id"
            KeyType: "HASH"
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
        TableName: ${self:custom.settings.${self:custom.myStage}.POSTS_TABLE}
        StreamSpecification:
          StreamViewType: NEW_IMAGE
